# These are supported funding model platforms

github: [shindesharad71] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
open_collective: # Replace with a single Open Collective username
custom: # Replace with a single custom sponsorship URL
